const mockData = [
    {
        id: 1,
        name: "3BHK Apartment for Rent in Bangalore",
        img: "https://via.placeholder.com/150",
        price: 1000,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        bedrooms: 3,
        description: "This is a description",
        address: "1234 Fake St",
    },
    {
        id: 2,
        name: "2 BHK Residential House for Rent",
        img: "https://img.staticmb.com/mbphoto/property/cropped_images/2024/Feb/25/Photo_h300_w450/71560249_4_PropertyImage633-8785897425547_300_450.jpg",
        price: 21000,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        bedrooms: 2,
        description:
            "2BHK Residential House for Rent in HSR Layout, Bangalore. The property is located in a prime location and is close to all the amenities. The property is available for family only.",
        address: "Electronic City, Bangalore",
    },
    {
        id: 3,
        name: "1 BHK Apartment for Rent in Mumbai",
        img: "https://via.placeholder.com/150",
        price: 5000,
        furnishing: "Unfurnished",
        bathrooms: 1,
        bedrooms: 1,
        description: "Affordable 1BHK apartment in the heart of Mumbai.",
        address: "Mumbai Central, Mumbai",
    },
    {
        id: 4,
        name: "3 BHK Villa for Rent in Hyderabad",
        img: "https://via.placeholder.com/150",
        price: 15000,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        bedrooms: 3,
        description: "Luxurious villa with all amenities included.",
        address: "Banjara Hills, Hyderabad",
    },
    {
        id: 5,
        name: "4 BHK Penthouse for Rent in Delhi",
        img: "https://via.placeholder.com/150",
        price: 35000,
        furnishing: "Semi-Furnished",
        bathrooms: 4,
        bedrooms: 4,
        description: "Spacious penthouse with a beautiful city view.",
        address: "Connaught Place, Delhi",
    },
    {
        id: 6,
        name: "2 BHK Apartment for Rent in Chennai",
        img: "https://via.placeholder.com/150",
        price: 12000,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        bedrooms: 2,
        description: "Modern apartment in a gated community.",
        address: "Adyar, Chennai",
    },
    {
        id: 7,
        name: "Studio Apartment for Rent in Pune",
        img: "https://via.placeholder.com/150",
        price: 8000,
        furnishing: "Unfurnished",
        bathrooms: 1,
        bedrooms: 1,
        description: "Compact and affordable studio apartment.",
        address: "Koregaon Park, Pune",
    },
    {
        id: 8,
        name: "5 BHK Bungalow for Rent in Kolkata",
        img: "https://via.placeholder.com/150",
        price: 50000,
        furnishing: "Fully Furnished",
        bathrooms: 5,
        bedrooms: 5,
        description: "Luxurious bungalow with a large garden.",
        address: "Salt Lake, Kolkata",
    },
    {
        id: 9,
        name: "2 BHK Apartment for Rent in Bangalore",
        img: "https://via.placeholder.com/150",
        price: 22000,
        furnishing: "Semi-Furnished",
        bathrooms: 2,
        bedrooms: 2,
        description: "Well-maintained apartment near tech parks.",
        address: "Whitefield, Bangalore",
    },
    {
        id: 10,
        name: "3 BHK House for Rent in Chennai",
        img: "https://via.placeholder.com/150",
        price: 18000,
        furnishing: "Fully Furnished",
        bathrooms: 3,
        bedrooms: 3,
        description: "Spacious house in a serene neighborhood.",
        address: "Velachery, Chennai",
    },
    {
        id: 11,
        name: "1 BHK Flat for Rent in Delhi",
        img: "https://via.placeholder.com/150",
        price: 7000,
        furnishing: "Unfurnished",
        bathrooms: 1,
        bedrooms: 1,
        description: "Affordable flat near public transport.",
        address: "Rohini, Delhi",
    },
    {
        id: 12,
        name: "4 BHK Duplex for Rent in Mumbai",
        img: "https://via.placeholder.com/150",
        price: 40000,
        furnishing: "Semi-Furnished",
        bathrooms: 4,
        bedrooms: 4,
        description: "Spacious duplex with modern amenities.",
        address: "Andheri West, Mumbai",
    },
    {
        id: 13,
        name: "2 BHK Flat for Rent in Hyderabad",
        img: "https://via.placeholder.com/150",
        price: 13000,
        furnishing: "Fully Furnished",
        bathrooms: 2,
        bedrooms: 2,
        description: "Comfortable flat in a prime location.",
        address: "Gachibowli, Hyderabad",
    },
    {
        id: 14,
        name: "3 BHK Apartment for Rent in Pune",
        img: "https://via.placeholder.com/150",
        price: 24000,
        furnishing: "Semi-Furnished",
        bathrooms: 3,
        bedrooms: 3,
        description: "Modern apartment with all facilities.",
        address: "Viman Nagar, Pune",
    },
    {
        id: 15,
        name: "5 BHK Villa for Rent in Bangalore",
        img: "https://via.placeholder.com/150",
        price: 45000,
        furnishing: "Fully Furnished",
        bathrooms: 5,
        bedrooms: 5,
        description: "Luxury villa with private pool.",
        address: "Whitefield, Bangalore",
    },
    {
        id: 16,
        name: "1 BHK House for Rent in Chennai",
        img: "https://via.placeholder.com/150",
        price: 9000,
        furnishing: "Unfurnished",
        bathrooms: 1,
        bedrooms: 1,
        description: "Affordable house in a quiet area.",
        address: "T. Nagar, Chennai",
    },
    {
        id: 17,
        name: "4 BHK Penthouse for Rent in Hyderabad",
        img: "https://via.placeholder.com/150",
        price: 38000,
        furnishing: "Fully Furnished",
        bathrooms: 4,
        bedrooms: 4,
        description: "Penthouse with a panoramic city view.",
        address: "Jubilee Hills, Hyderabad",
    },
    {
        id: 18,
        name: "3 BHK House for Rent in Kolkata",
        img: "https://via.placeholder.com/150",
        price: 20000,
        furnishing: "Semi-Furnished",
        bathrooms: 3,
        bedrooms: 3,
        description: "Spacious house with garden.",
        address: "New Town, Kolkata",
    },
    {
        id: 19,
        name: "2 BHK Apartment for Rent in Delhi",
        img: "https://via.placeholder.com/150",
        price: 15000,
        furnishing: "Unfurnished",
        bathrooms: 2,
        bedrooms: 2,
        description: "Modern apartment near metro station.",
        address: "Dwarka, Delhi",
    },
    {
        id: 20,
        name: "1 BHK Studio for Rent in Bangalore",
        img: "https://via.placeholder.com/150",
        price: 6000,
        furnishing: "Fully Furnished",
        bathrooms: 1,
        bedrooms: 1,
        description: "Compact studio in tech hub.",
        address: "Koramangala, Bangalore",
    }
];

export default mockData;
